packages:
  - "."

allowBuilds:
  '@tailwindcss/oxide': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: set this to true or false

overrides:
  fast-xml-parser: ">=5.7.0"
  drizzle-orm: ">=0.45.2"
  qs: ">=6.14.2"
  esbuild: ">=0.24.3"
  vite: ">=6.4.2"
